apiVersion: v1
kind: Pod
metadata:
  name: example1
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: my_secret_password
