---
# tasks file for nginx

- name: Ensure apache is not installed
  apt:
    name: apache2
    state: absent
  tags: [http_server, packages]
- name: Ensure nginx is present or install it
  apt:
    name: nginx
    state: present
    update_cache: true
  tags: [http_server, packages]
- name: Replace nginx site config
  copy:
    src: site.conf
    dest: /etc/nginx/sites-enabled/default
  tags: [http_server, system_config]
  notify:
   - Restart Nginx
