- hosts: all # server1
  become: yes
  tasks:
   - name: Ensure apache is not installed
     apt:
       name: apache2
       state: absent
   - name: Ensure nginx is present or install it
     apt:
       name: nginx
       state: present
       update_cache: true
   - name: Replace nginx site config
     copy:
       src: site.conf
       dest: /etc/nginx/sites-enabled/default
   - name: Restart nginx
     service:
       name: nginx
       state: restarted
   - name: Install rsync
     apt:
       name: rsync
       state: present
   - name: Install example site content
     synchronize:
       src: site/
       dest: /opt/html
       rsync_opts: --chown=www-data
       delete: yes
